/**
 * dsh-runtime-progress — the reference runtime-* plugin.
 *
 * Shows the canonical way a domain runtime plugin consumes the seam:
 *   1. inject the `runtimeSeam` service (declared by dsh-runtime-seam);
 *   2. declare domain facts through seam.setFact / seam.declareUnknown;
 *   3. register deterministic guards through seam.registerGuard (teaching
 *      reasons are generated by the seam, evidence format E1/E3/E5);
 *   4. subscribe to seam.onActivity to react to circuit-open / changes;
 *   5. own a settings namespace for plugin-specific policy (threshold, scope).
 *
 * This plugin's own policy (no-progress, evidence E4/E4b):
 *   - the seam already fingerprints repeated identical failures and opens a
 *     circuit (facts: capabilities.<tool>.state = failed);
 *   - this plugin additionally reacts: while a circuit is open, it can lock
 *     shell mutations (`pwsh`) so a looping session cannot burn more work.
 */
import Schema from "@deepseek-ai/schemastery";

export const name = "dsh-runtime-progress";
export const inject = ["runtimeSeam", "settings"];

const SETTINGS_SCHEMA = Schema.object({
  threshold: Schema.number().default(2),
  shellLockOnCircuit: Schema.boolean().default(false),
});

export function apply(ctx, _config) {
  const seam = ctx.runtimeSeam;
  const scope = ctx.settings.register("runtime-progress", SETTINGS_SCHEMA);

  // Domain facts live in the seam's registry — one vocabulary for everyone.
  seam.setFact("runtime-progress.status", "active", { authority: "runtime-progress" });
  seam.setFact("runtime-progress.shell-lock", "open", { authority: "runtime-progress" });

  // The seam owns the failure fingerprinting; this plugin owns the reaction
  // policy. Reacting through facts keeps it observable in the "Why" panel.
  ctx.effect(() =>
    seam.onActivity((entry) => {
      if (entry.kind !== "circuit") return;
      try {
        const settings = scope.get() ?? {};
        const lock = settings.shellLockOnCircuit ? "locked" : "open";
        seam.setFact("runtime-progress.shell-lock", lock, { authority: "runtime-progress" });
      } catch {
        /* settings read must never break the reaction */
      }
    }),
  );

  // Example guard: shell mutations are rejected while the lock fact is set.
  // The seam renders the teaching reason; rule order in the single monotonic
  // guard dispatcher is registration order (one rule per action).
  ctx.effect(() =>
    seam.registerGuard({
      action: "pwsh",
      factPath: "runtime-progress.shell-lock",
      predicate: (value) => value !== "locked",
      predicateText: "pwsh requires runtime-progress.shell-lock != locked",
      temporal: true,
      promise: false,
    }),
  );
}
